version: "3.7"

services:
    devops-example:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: devops-example
        restart: unless-stopped
        ports:
            - 3000:3000
