name: Build & test
on:
    push:
        branches:
            - "*"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout github repo
              uses: actions/checkout@v2
              with:
                lfs: true
            - name: Checkout LFS objects
              run: git lfs checkout
            - name: install dependencies
              run: yarn install
            - name: build
              run: yarn tsc
            - name: unit tests
              run: yarn jest tests/unit
            - name: integration tests
              run: sh scripts/integration_tests
